### PR TITLE
Add filetype detection

### PR DESCRIPTION
**Pull request by hal0**
Adds the `ftdetect/` directory, which is traversed in order to initialize autocmd's for filetype detection - in this case, detecting `.prm` files.

### CODE REVIEW

**Comment by blyoa** [comment]
Thank you for your pull-request and suggestion.

`ftdetect` files for Promela are unnecessary because Vim can already detect the Promela filetype.
Try `.pml` extension.

**Comment by hal0** [comment]
There are hefty amounts of Promela code that use the `.prm` extension, too. This doesn't hurt as `.prm` is not a standard extension provided by ViM to begin with.

**Comment by blyoa** [comment]
OK. I found some projects were using the `.prm` extension as Promela.
I will merge your contribution after I fix a license problem; I noticed that I was violating the Vim license.
When I fix the problem, I want to include a MIT license file for modified parts from the original  Vim scripts.

May I apply the MIT license on also parts of your contribution?

**Comment by hal0** [comment]
Yes, absolutely feel free.

**Comment by blyoa** [comment]
Thank you for your agreement and contribution.
I cherry-picked your commit at 57359653d18b24678680b755924ff4a1488cbaca.

**Pull request closed without merging**
